### ISSUE TITLE
Unhandled exception in thread started by <function deploy_app_jupiter at 0x7fe925bda400>

### ISSUE THREAD

**Issue by wangpu1029** [ANRGUSC/Jupiter#24]
**What happened (please include outputs or screenshots):**
RUN: python3 auto_deploy_system.py
OUTPUT: 

> Task mapper: Wave random selected
> Non pricing scheme selected
> CIRCE path-------------------------------------------
> /home/master2/Jupiter-develop/circe/original/
> 1
> Task mapper: Wave random selected
> Non pricing scheme selected
> CIRCE path-------------------------------------------
> /home/master2/Jupiter-develop/circe/original/
> [8080]
> ['coded1']
> coded1
>  * Serving Flask app "auto_deploy_system" (lazy loading)
>  * Environment: production
>    WARNING: This is a development server. Do not use it in a production deployment.
>    Use a production WSGI server instead.
>  * Debug mode: off
>  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)

> Task mapper: Wave random selected
> Non pricing scheme selected
> CIRCE path-------------------------------------------
> /home/master2/Jupiter-develop/circe/original/
> Deploy WAVE greedy mapper
> Task mapper: Wave random selected
> Non pricing scheme selected
> CIRCE path-------------------------------------------
> /home/master2/Jupiter-develop/circe/original/
> Exception Occurred
> F1112 15:12:32.327170  114217 proxy.go:160] listen tcp 127.0.0.1:8080: bind: address already in use
> Exception Occurred
> Exception Occurred
> Exception Occurred
> Task mapper: Wave random selected
> Non pricing scheme selected
> CIRCE path-------------------------------------------
> /home/master2/Jupiter-develop/circe/original/
> Exception Occurred
> *************************
> Network Profiling Information:
> {}
> Execution Profiling Information:
> {}
> *************************
> *************************
> WAVE mapper
> Task mapper: Wave random selected
> Non pricing scheme selected
> CIRCE path-------------------------------------------
> /home/master2/Jupiter-develop/circe/original/
> {'node1': ['Node1'], 'node2': ['Node2'], 'node3': ['Node3']}
> Task mapper: Wave random selected
> Non pricing scheme selected
> CIRCE path-------------------------------------------
> /home/master2/Jupiter-develop/circe/original/
> Unhandled exception in thread started by <function deploy_app_jupiter at 0x7fe925bda400>
> Traceback (most recent call last):
>   File "auto_deploy_system.py", line 361, in deploy_app_jupiter
>     k8s_jupiter_deploy(app_id,app_name,port)
>   File "auto_deploy_system.py", line 133, in k8s_jupiter_deploy
>     task_mapping_function(profiler_ips,execution_ips,node_names,app_name)
>   File "auto_deploy_system.py", line 63, in task_mapping
>     return f(args[0],args[3])
>   File "/home/master2/Jupiter-develop/mulhome_scripts/k8s_wave_scheduler.py", line 124, in k8s_wave_scheduler
>     ser_resp = api.create_namespaced_service(namespace, home_body)
>   File "/home/master2/.local/lib/python3.6/site-packages/kubernetes/client/apis/core_v1_api.py", line 6820, in create_namespaced_service
>     (data) = self.create_namespaced_service_with_http_info(namespace, body, **kwargs)
>   File "/home/master2/.local/lib/python3.6/site-packages/kubernetes/client/apis/core_v1_api.py", line 6905, in create_namespaced_service_with_http_info
>     collection_formats=collection_formats)
>   File "/home/master2/.local/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 321, in call_api
>     _return_http_data_only, collection_formats, _preload_content, _request_timeout)
>   File "/home/master2/.local/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 155, in __call_api
>     _request_timeout=_request_timeout)
>   File "/home/master2/.local/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 364, in request
>     body=body)
>   File "/home/master2/.local/lib/python3.6/site-packages/kubernetes/client/rest.py", line 266, in POST
>     body=body)
>   File "/home/master2/.local/lib/python3.6/site-packages/kubernetes/client/rest.py", line 222, in request
>     raise ApiException(http_resp=r)
> kubernetes.client.rest.ApiException: (409)
> Reason: Conflict
> HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json', 'Date': 'Tue, 12 Nov 2019 07:12:33 GMT', 'Content-Length': '208'})
> HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"services \"coded1-home\" already exists","reason":"AlreadyExists","details":{"name":"coded1-home","kind":"services"},"code":409}

**Environment:**

- Jupiter version: 4.0

- Kubernetes version (kubectl version): v1.15.2

- OS: Ubuntu 18.04

- Python version: 3.6.9

**Comment by caravansary83** [comment]
In auto_deploy_system.py:

If it is the first time using Jupiter, k8s_profiler_scheduler() and exec_profiler_function(app_id) should be used to spin up all the profilers. Once all the profilers pod have been set up, you can use get_all_profilers() and get_all_execs(app_id) to retrieve the profiler information.

**Comment by jasonatran** [comment]
@wangpu1029 I wanted to check in here to see if this issue has been resolved. Any luck?

**Comment by jasonatran** [comment]
We're going to undergo a lot of changes with a more stable way to bootstrap a new cluster to avoid issues like these. I'm going to close this for now. Please open up another issue if you'd like this resolved.
